jobs:
  - name: testdup2mani
    type: manifest
    steps:
      - IN: image1
       # versionNumber: 01234
     # - IN: t111     

  - name: test-runSh-webhookv2
    type: runSh
    on_start:
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    steps:
      #- IN: notify-slack
     # - IN: langtest_u14golall
    #  - OUT: trigger
      - OUT: state
      #- OUT: filejfrog
     # - OUT: cliconfig
      #- OUT: sampleNod_ciRepo
      #- OUT: allpl-release11
     # - OUT: my_hipchat_key
     # - OUT: slackIN
      - OUT: script3
      - OUT: image1
     # - OUT: testdup2mani
      #- OUT: twoRunsh
      #- OUT: kube-dockeropts
      #- OUT: test-trigger
      #- OUT: test_params
     # - OUT: allpl-lb
     # - OUT: allpl-scale2
      #- OUT: allpl-version
   #   - IN: testintegrationwebhook
      - TASK:  
        #- script: ./IN/script3/gitRepo/echo.sh
        - script: echo "---integration typed resource---"
        - script: echo "int name ------->-"$TESTINTEGRATIONWEBHOOK_NAME
        - script: echo "webhookurl ------->-"$TESTINTEGRATIONWEBHOOK_INTEGRATION_WEBHOOKURL
        - script: echo "authorization ------->---"$TESTINTEGRATIONWEBHOOK_INTEGRATION_AUTHORIZATION
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    on_cancel:
      - script: echo "This works on_always"
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
      
  - name: twoRunsh
    type: runSh
    steps:
    
   #   - IN: testintegrationwebhook
      - TASK:  
        - script: echo "test script is showing"
        
  - name: allpl-release11
    type: release
    steps:
      - IN: allpl-version
    
         #versionName: testrelease
      - TASK: managed
        bump: beta
   
