jobs:
  - name: testdup2mani
    type: manifest
    steps:
      - IN: image1
       # versionNumber: 01234
     # - IN: t111     

  - name: test-runSh-webhookv2
    type: runSh
   # runtime:
    #  architecture: aarch64
    #  os: Ubuntu_16.04
    #  container: true  #default
    on_start:
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    steps:
      #- IN: notify-slack
     # - IN: langtest_u14golall
      - OUT: trigger
      - OUT: state
      - OUT: filejfrog
      - OUT: cliconfig
      - OUT: sampleNod_ciRepo
      - OUT: allpl-release11
      - OUT: my_hipchat_key
     # - OUT: slackIN
      - OUT: script3
      - OUT: image1
      - OUT: testdup2mani
      - OUT: OUTrunSh
     # - OUT: twoRunsh
      - OUT: kube-dockeropts
      - OUT: test-trigger
      - OUT: test_params
      - OUT: allpl-lb
      - OUT: allpl-scale2
      #- IN: script3
      - OUT: allpl-version
   #   - IN: testintegrationwebhook
      - TASK:  
       # - script: ./IN/script3/gitRepo/echo.sh
        - script: echo versionName=$SCRIPT3_VERSIONNUMBER > "$JOB_STATE/$IMAGE1.env"
        #- script: echo commitSHA=$SCRIPT3_COMMIT >> "$JOB_STATE/$IMAGE1.env" 
        - script: cat "$JOB_STATE/$IMAGE1.env"
        - script: echo versionName=$SCRIPT3_VERSIONNUMBER > "$JOB_STATE/$TESTRUNSHWEBHOOKV2.env"
        - script: cat "$JOB_STATE/$TESTRUNSHWEBHOOKV2.env"
        - script: echo "---integration typed resource---"
        - script: echo "int name ------->-"$TESTINTEGRATIONWEBHOOK_NAME
        - script: echo "webhookurl ------->-"$TESTINTEGRATIONWEBHOOK_INTEGRATION_WEBHOOKURL
        - script: echo "authorization ------->---"$TESTINTEGRATIONWEBHOOK_INTEGRATION_AUTHORIZATION
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
    on_cancel:
      - script: echo "This works on_always"
      - NOTIFY: newemailtest
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-slack
      
      
      
      
      
  - name: twoRunsh
    type: runSh
   # runtime:
    #  architecture: x86_64
    #  os: Ubuntu_16.04
    #  container: true  #default
    steps:
      - IN: trigger
      - IN: state
      - IN: filejfrog
      - IN: cliconfig
      - IN: sampleNod_ciRepo
      - IN: allpl-release11
      - IN: my_hipchat_key
     # - OUT: slackIN
      - IN: script3
      - IN: image1
      - IN: testdup2mani
      - IN: INrunSh
     # - IN: twoRunsh
      - IN: kube-dockeropts
      - IN: test-trigger
      - IN: test_params
      - IN: allpl-lb
      - IN: allpl-scale2
     # - IN: script3
      - IN: allpl-version
    
   #   - IN: testintegrationwebhook
      - TASK:  
        - script: ./IN/script3/gitRepo/echo.sh
        - script: echo "test script is showing"
        
  - name: allpl-release11
    type: release
    steps:
      - IN: allpl-version
    
         #versionName: testrelease
      - TASK: managed
        bump: beta
   
  - name: INrunSh
    type: runSh
   # allowPublicAccess: true
    steps:
     # - IN: script3
    #  - IN: state
      #- IN: t111
      - TASK:
         #- script: ./IN/sacript3/gitRepo/echo.sh
         - script: echo 'api'
         - script: echo 'test'
         
  - name: OUTrunSh
    type: runSh
   # allowPublicAccess: true
    steps:
     # - IN: script3
    #  - IN: state
      #- IN: t111
      - TASK:
         #- script: ./IN/script3/gitRepo/echo.sh
         - script: echo 'api'
         - script: echo 'test'
